include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-dom0-build.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm-fedora-build.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm-debian-build.yml'
#  - project: 'QubesOS/qubes-continuous-integration'
#    file: '/r4.1/gitlab-vm-archlinux-build.yml'

prep:sources:
  extends: .components_prepare
  variables:
    GIT_CLONE_FAST: 0
    BUILDERCONF: scripts/gitlab-builder.conf
  script:
    # prepare for dummy value, actual sources are downloaded later
    - ~/qubes-builder/scripts/gitlab-prepare "builder-rpm"
    - cp ~/qubes-builder/scripts/gitlab-builder.conf ~/qubes-builder/builder.conf
    - git config --global user.email "user@example.com"
    - git config --global user.name "builder"
    - ./utils/get-prs-sources
    - tar cJf $CI_PROJECT_DIR/qubes-builder.tar.xz --strip-components=1 -C ~/ qubes-builder

publish:repo:
  # we enforce tags to not override it
  tags:
    - docker
  needs:
    - build:dom0-fc32
    - build:vm-buster
    - build:vm-bullseye
    - build:vm-fc33
    - build:vm-fc34
  stage: publish
  artifacts:
    expire_in: 7 days
    paths:
    - repo
  script:
    - sudo dnf -y install rpm-sign
    - gpg --generate-key --batch < utils/repo-key.gpgbatch
    - ./utils/combine-and-sign-repo "$PWD/qubes-packages-mirror-repo" "$PWD/repo" TEST
    - gpg -a --export > repo/key.pub

